codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 70%
        informational: true

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: true

ignore:
  - "target/**"
  - "tests/data/**"
  - "src/main.rs"
